spring:
  application:
    name: package-burst
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 6484
  error:
    whitelabel:
      enabled: false